filebeat.inputs:
  - type: filestream
    id: vpn-syslog-input
    enabled: true
    paths:
      - /var/log/app/vpn_logs.log

    fields_under_root: true
    fields:
      source_type: vpn
      log_type: vpn
      source_format: syslog
      env: dev
      collector: filebeat

output.kafka:
  hosts: ["kafka:9092"]
  topic: "raw_logs"
  required_acks: 1
  compression: gzip
  codec.json:
    pretty: false

processors:
  - add_host_metadata: ~
  - drop_fields:
      fields: ["agent", "ecs", "input"]
      ignore_missing: true
